apiVersion: skaffold/v2alpha4
kind: Config

build:
  tagPolicy:
    envTemplate:
      template: "{{.VER}}"
  artifacts:
    - image: board-fe
      jib:
        args:
          - -DskipTests

profiles:
  - name: kind
    build:
      local:
        push: false
      artifacts:
        - image: board-fe
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"
    deploy:
      kubectl:
        manifests:
          - k8s/kind/board-fe-deploy.yaml
          - k8s/kind/board-fe-svc.yaml

  - name: kind-push
    build:
      local:
        push: true
      artifacts:
        - image: jacksonkim/board-fe
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"
