apiVersion: apps/v1

kind: Deployment

metadata:
  name: board-fe
  namespace: front
  labels:
    env: dev

spec:
  #replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev

    spec:
      containers:
        - name: board-fe
          image: 723184425190.dkr.ecr.ap-northeast-2.amazonaws.com/board-fe
          ports:
          - containerPort: 8080
